### ISSUE TITLE
Beta package on the primary channel/label

### ISSUE THREAD

**Issue by djhoese** [conda-forge/pika-feedstock#13]
It seems 1.0.0b1 is on the primary conda-forge channel and is what a user will get by default. Is this intended that all users will get a beta version of the package? Or should this version be moved to the `dev` label?

**Comment by ltalirz** [comment]
It's a workaround - the problem is that there is currently no way to depend on packages from the `dev` channel.

See discussion [here](https://github.com/conda-forge/staged-recipes/pull/6948#issuecomment-435620606), I'm just following the advice I was given by the admins... happy to do it a better way!

**Comment by ltalirz** [comment]
#16 should resolve this workaround - the latest version is now 1.0
